import type { Metadata } from "next";
import { ClerkProvider, SignedIn, UserButton } from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { LanguageProvider } from "@/context/LanguageContext";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
import LanguageSwitcher from "@/components/LanguageSwitcher";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen flex flex-col`}
        >
          <LanguageProvider>
            <header className="fixed top-0 left-0 right-0 z-50 bg-gray-100 h-16 flex items-center justify-between px-4">
              <LanguageSwitcher />
              <SignedIn>
                <UserButton />
              </SignedIn>
            </header>

            {/* Main con margen arriba igual al header, ocupa resto y permite scroll */}
            <main className="grow pt-16">
              {children}
            </main>
          </LanguageProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
